const $=id=>document.getElementById(id);const n=id=>{const e=$(id);return e?parseFloat(e.value)||0:0};const set=(id,v)=>{const e=$(id);if(e)e.textContent=v};const val=(id,v)=>{const e=$(id);if(e)e.value=v};const fmt=(v,d=2)=>Number(v).toLocaleString('id-ID',{minimumFractionDigits:d,maximumFractionDigits:d});
function cycleTruck(){const t=['loading','travelLoaded','maneuverDump','dumping','maneuverEmpty','travelEmpty'].reduce((s,id)=>s+n(id),0);set('cycleSeconds',fmt(t));set('cycleMinutes','= '+fmt(t/60)+' menit');val('mfCta',t.toFixed(2));val('truckCTSec',t.toFixed(2));return t}
function cycleExc(){const t=n('digging')+n('swingLoaded')+n('dumpingExc')+n('swingEmpty');set('excCycleSeconds',fmt(t));set('excCycleMinutes','= '+fmt(t/60,3)+' menit');val('excCTProd',t.toFixed(2));return t}
function matchFactor(){const c=cycleTruck(),mf=(n('numExc')*c)>0?n('numTruck')*n('loadingTimeMF')*n('passes')/(n('numExc')*c):NaN;set('mfValue',isFinite(mf)?fmt(mf):'—');const b=$('mfStatusBadge'),t=$('mfStatusText');if(b&&t){if(!isFinite(mf)){b.textContent='DATA';t.textContent='Data belum valid'}else if(mf<.98){b.textContent='MF < 1';t.textContent='Alat gali-muat cenderung menunggu'}else if(mf<=1.02){b.textContent='MF ≈ 1';t.textContent='Sinkronisasi ideal'}else{b.textContent='MF > 1';t.textContent='Dump truck cenderung menunggu'}}}
function truckProduction(){const c=n('excCTProd'),p=c?(3600/c)*n('bucketCap')*n('fillFactor')*n('swellFactor')*n('effTruck')/100:NaN;set('truckProdOutput',isFinite(p)?fmt(p):'—')}
function excavatorProduction(){const c=n('truckCTSec'),p=c?(3600/c)*n('bucketCap2')*n('fillFactor2')*n('effExc')/100:NaN;set('excProdOutput',isFinite(p)?fmt(p):'—')}
function support(){const ct=n('dzD')/Math.max(n('dzVf'),.0001)+n('dzD')/Math.max(n('dzVr'),.0001)+n('dzZ');const q=ct?(n('dzB')*n('dzH')*n('dzD')*n('dzFb')*60*n('dzE'))/ct:NaN;set('dzOut',isFinite(q)?fmt(q):'—');const grct=n('grJ')/Math.max(n('grVf'),.0001)+n('grJ')/Math.max(n('grVr'),.0001)+n('grZ');const qr=grct?(n('grP')**2*n('grJ')*60*n('grE')*n('grFK'))/grct:NaN;set('grOut',isFinite(qr)?fmt(qr):'—');const mg=n('mgV')*(n('mgLe')-n('mgLo'))*1000*n('mgE');set('mgOut',isFinite(mg)?fmt(mg):'—');const width=n('mgLe2')-n('mgLo2');const trips=width>0?n('mgW')/width*n('mgNPass'):NaN;set('mgTripsOut',isFinite(trips)?fmt(trips):'—');const hours=(isFinite(trips)&&n('mgV2')>0&&n('mgE2')>0)?trips*n('mgD')/(n('mgV2')*1000*n('mgE2')):NaN;set('mgTimeOut',isFinite(hours)?fmt(hours):'—');const cp=n('cpN')>0?n('cpW')*n('cpV')*n('cpH')*1000*n('cpE')/n('cpN'):NaN;set('cpOut',isFinite(cp)?fmt(cp):'—')}
function availability(){const W=n('working'),R=n('repair'),S=n('standby');const vals=[W/(W+R)*100,(W+S)/(W+R+S)*100,W/(W+S)*100,W/(W+R+S)*100];['ma','pa','ua','eu'].forEach((id,i)=>set(id,isFinite(vals[i])?fmt(vals[i])+' %':'—'))}
function roadSimple(){const a=n('ddtActualCbr'),t=n('ddtTargetSimple');set('roadStatus',a>=t?'RECOMMENDED':'NOT RECOMMENDED')}
function recalc(){cycleTruck();cycleExc();matchFactor();truckProduction();excavatorProduction();support();availability();roadSimple()}
function openModule(id){document.querySelectorAll('.module-section').forEach(s=>s.classList.remove('active'));const t=$(id);if(t)t.classList.add('active');document.querySelectorAll('.nav-item').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id));window.scrollTo({top:0,behavior:'smooth'});}
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',recalc));document.querySelectorAll('.nav-item').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href')?.slice(1);if(id){e.preventDefault();openModule(id)}}));document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openModule(b.dataset.open)));recalc()});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));