(function(){
  const $=id=>document.getElementById(id);
  const n=id=>{const v=parseFloat($(id)?.value);return Number.isFinite(v)?v:0};
  const fmt=(v,d=2)=>Number(v).toLocaleString('id-ID',{minimumFractionDigits:d,maximumFractionDigits:d});
  function truckCTmin(){return (typeof cycleTruck==='function'?cycleTruck():['loading','travelLoaded','maneuverDump','dumping','maneuverEmpty','travelEmpty'].reduce((s,id)=>s+n(id),0))/60}
  function excCTmin(){return (typeof cycleExc==='function'?cycleExc():['digging','swingLoaded','dumpingExc','swingEmpty'].reduce((s,id)=>s+n(id),0))/60}
  window.matchFactor=function(){const Na=n('numTruck'),Nm=n('numExc'),CTa=truckCTmin(),CTm=n('loadingTimeMF')||excCTmin(),passes=n('passes'),tm=passes*CTm,mf=(Nm>0&&CTa>0)?(Na*tm)/(Nm*CTa):NaN;if($('mfValue'))$('mfValue').textContent=Number.isFinite(mf)?fmt(mf):'—';if($('mfCta'))$('mfCta').value=CTa.toFixed(2);const b=$('mfStatusBadge'),t=$('mfStatusText');if(b&&t){if(!Number.isFinite(mf)){b.textContent='DATA';t.textContent='Data belum valid'}else if(Math.abs(mf-1)<.02){b.textContent='MF ≈ 1';t.textContent='Alat muat dan angkut serasi'}else if(mf<1){b.textContent='MF < 1';t.textContent='Alat muat cenderung menunggu'}else{b.textContent='MF > 1';t.textContent='Alat angkut cenderung antre'}}};
  window.truckProduction=function(){const CTa=n('excCTProd'),q=n('prodPass')*n('bucketCap')*n('fillFactor')*n('swellFactor'),E=n('effTruck')/100,p=CTa>0?(60/CTa)*q*E:NaN;if($('truckProdOutput'))$('truckProdOutput').textContent=Number.isFinite(p)?fmt(p):'—'};
  window.excavatorProduction=function(){const CTm=n('truckCTSec'),q=n('bucketCap2')*n('fillFactor2')*n('swellFactor'),E=n('effExc')/100,p=CTm>0?(60/CTm)*q*E:NaN;if($('excProdOutput'))$('excProdOutput').textContent=Number.isFinite(p)?fmt(p):'—'};
  function labels(){const lm=$('loadingTimeMF')?.closest('label')?.querySelector('span');if(lm)lm.innerHTML='CTm - Cycle Time Alat Muat <small>(menit)</small>';const mc=$('mfCta')?.closest('label')?.querySelector('span');if(mc)mc.innerHTML='CTa - Cycle Time Alat Angkut <small>(menit)</small>';const tf=$('excCTProd')?.closest('label')?.querySelector('span');if(tf)tf.innerHTML='CTa - Cycle Time Alat Angkut <small>(menit)</small>';const ef=$('truckCTSec')?.closest('label')?.querySelector('span');if(ef)ef.innerHTML='CTm - Cycle Time Alat Muat <small>(menit)</small>';const mfFormula=document.querySelector('#match-factor .formula-display');if(mfFormula)mfFormula.innerHTML='MF = <span>Na × (n × CTm)</span><hr><span>Nm × CTa</span><small style="display:block;margin-top:8px">tm = n × CTm</small>';const trFormula=document.querySelector('#produktivit-as .formula-display');if(trFormula)trFormula.textContent='Q = (60 / CTa) × (n × q × FF × SF) × E';const exFormula=document.querySelector('#produktivitas-exc .formula-display');if(exFormula)exFormula.innerHTML='P = (60 / CTm) × q × FF × SF × E'}
  function sync(){const cm=truckCTmin(),em=excCTmin();if($('mfCta')&&document.activeElement!==$('mfCta'))$('mfCta').value=cm.toFixed(2);if($('loadingTimeMF')&&document.activeElement!==$('loadingTimeMF')&&$('loadingTimeMF').dataset.autoset!=='0'){$('loadingTimeMF').value=em.toFixed(3);$('loadingTimeMF').dataset.autoset='1'}if($('excCTProd')&&document.activeElement!==$('excCTProd')&&$('excCTProd').dataset.autoset!=='0')$('excCTProd').value=cm.toFixed(2);if($('truckCTSec')&&document.activeElement!==$('truckCTSec')&&$('truckCTSec').dataset.autoset!=='0')$('truckCTSec').value=em.toFixed(3);matchFactor();truckProduction();excavatorProduction()}
  function unlock(){['excCTProd','truckCTSec','loadingTimeMF'].forEach(id=>{const el=$(id);if(el){el.removeAttribute('readonly');el.dataset.autoset='1';el.addEventListener('focus',()=>el.dataset.autoset='0');el.addEventListener('input',()=>{if(id==='loadingTimeMF')matchFactor();if(id==='excCTProd')truckProduction();if(id==='truckCTSec')excavatorProduction()})}});labels();document.querySelectorAll('#core-productivity input').forEach(el=>el.addEventListener('input',()=>{matchFactor();truckProduction();excavatorProduction()}));['loading','travelLoaded','maneuverDump','dumping','maneuverEmpty','travelEmpty','digging','swingLoaded','dumpingExc','swingEmpty'].forEach(id=>$(id)?.addEventListener('input',sync));sync()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',unlock);else unlock();
})();