(function(){
  const $=id=>document.getElementById(id);
  const raw=id=>$(id)?.value??'';
  const n=id=>{const v=parseFloat(String(raw(id)).trim().replace(/\s/g,'').replace(/,/g,'.'));return Number.isFinite(v)?v:0};
  const fmt=(v,d=2)=>Number(v).toLocaleString('id-ID',{minimumFractionDigits:d,maximumFractionDigits:d});
  let mfManual=false, haulManual=false, excManual=false;
  const editable=id=>{const e=$(id);if(!e)return;e.removeAttribute('readonly');e.removeAttribute('disabled');e.style.pointerEvents='auto';e.type='text';e.inputMode='decimal';if(!e.dataset.commaReady){e.dataset.commaReady='1';e.addEventListener('input',()=>{if(id==='mfCta')mfManual=true;if(id==='excCTProd')haulManual=true;if(id==='truckCTSec')excManual=true;if(id==='mfCta')window.matchFactor();if(['excCTProd','bucketCap','fillFactor','swellFactor','effTruck'].includes(id))window.truckProduction();if(['truckCTSec','bucketCap2','fillFactor2','swellFactor','effExc'].includes(id))window.excavatorProduction()});e.addEventListener('change',()=>{if(id==='mfCta')mfManual=true;if(id==='excCTProd')haulManual=true;if(id==='truckCTSec')excManual=true})}};
  const formulaBox=(selector,html)=>{const el=document.querySelector(selector);if(el)el.innerHTML=html};
  function labels(){const set=(id,t)=>{const s=$(id)?.closest('label')?.querySelector('span');if(s)s.innerHTML=t};set('loadingTimeMF','tm - Cycle Time Muat Excavator <small>(menit/pass)</small>');set('mfCta','ta / CTa - Cycle Time Hauler <small>(menit)</small>');set('excCTProd','CTa - Cycle Time Hauler <small>(menit)</small>');set('bucketCap','q - Kapasitas muatan nominal <small>(m³)</small>');set('fillFactor','FF - Fill Factor');set('swellFactor','SF - Swell Factor');set('effTruck','E - Efisiensi kerja alat <small>(%)</small>');set('truckCTSec','CTm - Cycle Time alat muat <small>(menit)</small>');set('bucketCap2','q - Kapasitas bucket nominal <small>(m³)</small>');set('fillFactor2','FF - Fill Factor');set('effExc','E - Efisiensi kerja alat <small>(%)</small>');formulaBox('#match-factor .formula-display','<div>MF =</div><div style="display:inline-block;text-align:center;line-height:1.25"><span>Na × tm × n</span><hr style="margin:3px 0"><span>Nm × ta</span></div><small id="mfFormulaCalc" style="display:block;margin-top:8px">Substitusi: —</small>');formulaBox('#produktivit-as .formula-display','<div>Q =</div><div style="display:inline-block;text-align:center;line-height:1.25"><span>60 × q × FF × SF × E</span><hr style="margin:3px 0"><span>CTa</span></div><small id="haulFormulaCalc" style="display:block;margin-top:8px">Substitusi: —</small><small style="display:block;margin-top:4px">CTa = cycle time hauler (menit)</small>');formulaBox('#produktivitas-exc .formula-display','<div>Q =</div><div style="display:inline-block;text-align:center;line-height:1.25"><span>60 × q × FF × SF × E</span><hr style="margin:3px 0"><span>CTm</span></div><small id="excFormulaCalc" style="display:block;margin-top:8px">Substitusi: —</small>');}
  function updateHaulFormula(){const c=n('excCTProd'),q=n('bucketCap'),FF=n('fillFactor'),SF=n('swellFactor'),E=n('effTruck')/100;const v=c>0?(60/c)*q*FF*SF*E:NaN;const el=$('haulFormulaCalc');if(el)el.textContent=Number.isFinite(v)?`Substitusi: (60 × ${fmt(q)} × ${fmt(FF)} × ${fmt(SF)} × ${fmt(E)}) ÷ ${fmt(c)} = ${fmt(v)} m³/jam`:'Substitusi: —'}
  function updateMFFormula(Na,Nm,tm,passes,ta,v){const el=$('mfFormulaCalc');if(el)el.textContent=Number.isFinite(v)?`Substitusi: (${fmt(Na)} × ${fmt(tm)} × ${fmt(passes)}) ÷ (${fmt(Nm)} × ${fmt(ta)}) = ${fmt(v)}`:'Substitusi: —'}
  function updateExcFormula(){const c=n('truckCTSec'),q=n('bucketCap2'),FF=n('fillFactor2'),SF=n('swellFactor'),E=n('effExc')/100;const v=c>0?(60/c)*q*FF*SF*E:NaN;const el=$('excFormulaCalc');if(el)el.textContent=Number.isFinite(v)?`Substitusi: (60 × ${fmt(q)} × ${fmt(FF)} × ${fmt(SF)} × ${fmt(E)}) ÷ ${fmt(c)} = ${fmt(v)} m³/jam`:'Substitusi: —'}
  window.matchFactor=function(){const Na=n('numTruck'),Nm=n('numExc'),tm=n('loadingTimeMF'),passes=n('passes'),ta=n('mfCta');const v=(Nm>0&&ta>0)?Na*tm*passes/(Nm*ta):NaN;if($('mfValue'))$('mfValue').textContent=Number.isFinite(v)?fmt(v):'—';updateMFFormula(Na,Nm,tm,passes,ta,v)};
  window.truckProduction=function(){const c=n('excCTProd'),q=n('bucketCap'),FF=n('fillFactor'),SF=n('swellFactor'),E=n('effTruck')/100;const v=c>0?(60/c)*q*FF*SF*E:NaN;if($('truckProdOutput'))$('truckProdOutput').textContent=Number.isFinite(v)?fmt(v):'—';updateHaulFormula()};
  window.excavatorProduction=function(){const c=n('truckCTSec'),q=n('bucketCap2'),FF=n('fillFactor2'),SF=n('swellFactor'),E=n('effExc')/100;const v=c>0?(60/c)*q*FF*SF*E:NaN;if($('excProdOutput'))$('excProdOutput').textContent=Number.isFinite(v)?fmt(v):'—';updateExcFormula()};
  function install(){labels();['mfCta','excCTProd','truckCTSec','loadingTimeMF','bucketCap','fillFactor','swellFactor','effTruck','bucketCap2','fillFactor2','effExc'].forEach(editable);if($('mfCta')&&!mfManual&&$('mfCta').value==='955')$('mfCta').value=(['loading','travelLoaded','maneuverDump','dumping','maneuverEmpty','travelEmpty'].reduce((s,id)=>s+n(id),0)/60).toFixed(2);if($('excCTProd')&&!haulManual&&$('excCTProd').value==='15.91')$('excCTProd').value=(['loading','travelLoaded','maneuverDump','dumping','maneuverEmpty','travelEmpty'].reduce((s,id)=>s+n(id),0)/60).toFixed(2);if($('truckCTSec')&&!excManual&&$('truckCTSec').value==='955')$('truckCTSec').value=(['loading','travelLoaded','maneuverDump','dumping','maneuverEmpty','travelEmpty'].reduce((s,id)=>s+n(id),0)/60).toFixed(2);window.matchFactor();window.truckProduction();window.excavatorProduction()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,100));else setTimeout(install,100);new MutationObserver(()=>setTimeout(install,20)).observe(document.documentElement,{childList:true,subtree:true});
})();