/* Visible Formula Layer — polished Availability + Support Equipment + Road */
(()=>{
  const $=id=>document.getElementById(id);
  const n=id=>{const v=String($(id)?.value??'').trim().replace(/\s/g,'').replace(',','.');const x=parseFloat(v);return Number.isFinite(x)?x:0};
  const f=(v,d=2)=>Number(v).toLocaleString('id-ID',{minimumFractionDigits:d,maximumFractionDigits:d});
  const unit=(v,u)=>`<b class="formula-result">${f(v)} ${u}</b>`;
  const css=`
    .formula-calc{margin:16px 0;padding:18px 20px;border:1px solid rgba(37,99,235,.14);border-radius:16px;background:linear-gradient(135deg,#f8fbff,#ffffff);box-shadow:0 6px 18px rgba(15,23,42,.06);line-height:1.6;color:#334155}
    .formula-calc .formula-title{display:flex;align-items:center;gap:8px;font-size:13px;font-weight:800;letter-spacing:.06em;color:#1d4ed8;margin-bottom:14px}
    .formula-calc .formula-title span{display:inline-flex;width:25px;height:25px;align-items:center;justify-content:center;border-radius:8px;background:#dbeafe}
    .formula-calc .formula-line{padding:10px 12px;margin:7px 0;border-radius:10px;background:#f8fafc;border:1px solid #e2e8f0;font-size:14px}
    .formula-calc .formula-label{display:block;font-size:11px;font-weight:800;color:#64748b;text-transform:uppercase;letter-spacing:.06em;margin-bottom:3px}
    .formula-calc .formula-eq{font-weight:600;color:#0f172a}
    .formula-calc .formula-result{color:#1d4ed8;font-size:15px}
    .availability-formula{margin-top:18px}
    .availability-formula .avail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}
    .availability-formula .avail-item{padding:12px 14px;border:1px solid #e2e8f0;border-radius:12px;background:#fff}
    .availability-formula .avail-name{font-weight:800;font-size:13px;color:#0f172a;margin-bottom:4px}
    .availability-formula .avail-formula{font-size:13px;color:#475569}
    @media(max-width:700px){.availability-formula .avail-grid{grid-template-columns:1fr}.formula-calc{padding:15px}}
  `;
  function style(){if(!document.getElementById('formula-polish-css')){const s=document.createElement('style');s.id='formula-polish-css';s.textContent=css;document.head.appendChild(s)}}
  function addFormula(outputId,htmlFn,key){const out=$(outputId);if(!out)return;const card=out.closest('.sub-card,.tool-card,.calc-card,.module-section,article,section')||out.parentElement;if(!card)return;let box=card.querySelector(`[data-formula-box="${key}"]`);if(!box){box=document.createElement('div');box.className='formula-calc';box.dataset.formulaBox=key;out.parentElement?.insertAdjacentElement('beforebegin',box)}const run=()=>{box.innerHTML=`<div class="formula-title"><span>ƒ</span> RUMUS & SUBSTITUSI</div>${htmlFn()}`};card.querySelectorAll('input,select').forEach(x=>{x.addEventListener('input',run);x.addEventListener('change',run)});run()}
  function install(){
    style();
    addFormula('dzOut',()=>{const B=n('dzB'),H=n('dzH'),D=n('dzD'),Fb=n('dzFb'),Vf=n('dzVf'),Vr=n('dzVr'),Z=n('dzZ'),E=n('dzE');const q=B*H*D*Fb,ct=D/Vf+D/Vr+Z,v=ct?(q*60*E)/ct:NaN;return `<div class="formula-line"><span class="formula-label">Rumus</span><span class="formula-eq">Q = (B × H × D × Fb × 60 × E) ÷ CT</span></div><div class="formula-line"><span class="formula-label">Substitusi</span><span class="formula-eq">(${f(B)} × ${f(H)} × ${f(D)} × ${f(Fb)} × 60 × ${f(E)}) ÷ ${f(ct)} = ${Number.isFinite(v)?unit(v,'m³/jam'):'—'}</span></div>`},'dozer');
    addFormula('grOut',()=>{const P=n('grP'),J=n('grJ'),Vf=n('grVf'),Vr=n('grVr'),Z=n('grZ'),E=n('grE'),FK=n('grFK');const ct=J/Vf+J/Vr+Z,v=ct?(P**2*J*60*E*FK)/ct:NaN;return `<div class="formula-line"><span class="formula-label">Rumus</span><span class="formula-eq">Q = (P² × J × 60 × E × FK) ÷ CT</span></div><div class="formula-line"><span class="formula-label">Substitusi</span><span class="formula-eq">(${f(P)}² × ${f(J)} × 60 × ${f(E)} × ${f(FK)}) ÷ ${f(ct)} = ${Number.isFinite(v)?unit(v,'m²/jam'):'—'}</span></div>`},'grader');
    addFormula('mgOut',()=>{const V=n('mgV'),Le=n('mgLe'),Lo=n('mgLo'),E=n('mgE');const q=V*(Le-Lo)*1000*E;return `<div class="formula-line"><span class="formula-label">Rumus</span><span class="formula-eq">Q = V × (Lebar kerja − overlap) × 1000 × E</span></div><div class="formula-line"><span class="formula-label">Substitusi</span><span class="formula-eq">${f(V)} × (${f(Le)} − ${f(Lo)}) × 1000 × ${f(E)} = ${unit(q,'m²/jam')}</span></div>`},'motor-grader');
    addFormula('mgTimeOut',()=>{const W=n('mgW'),Le=n('mgLe2'),Lo=n('mgLo2'),np=n('mgNPass'),D=n('mgD'),V=n('mgV2'),E=n('mgE'),width=Le-Lo,trips=width?W/width*np:NaN,h=V&&E?(trips*D)/(V*1000*E):NaN;return `<div class="formula-line"><span class="formula-label">Rumus</span><span class="formula-eq">Trip = (Lebar area ÷ lebar efektif) × n</span></div><div class="formula-line"><span class="formula-label">Substitusi</span><span class="formula-eq">(${f(W)} ÷ (${f(Le)} − ${f(Lo)})) × ${f(np,0)} = ${f(trips)} trip</span></div><div class="formula-line"><span class="formula-label">Waktu</span><span class="formula-eq">(Trip × Distance) ÷ (V × 1000 × E) = ${Number.isFinite(h)?unit(h,'jam'):'—'}</span></div>`},'motor-time');
    addFormula('cpOut',()=>{const W=n('cpW'),V=n('cpV'),H=n('cpH'),E=n('cpE'),N=n('cpN'),q=N?(W*V*H*1000*E)/N:NaN;return `<div class="formula-line"><span class="formula-label">Rumus</span><span class="formula-eq">Q = (W × V × H × 1000 × E) ÷ N</span></div><div class="formula-line"><span class="formula-label">Substitusi</span><span class="formula-eq">(${f(W)} × ${f(V)} × ${f(H)} × 1000 × ${f(E)}) ÷ ${f(N)} = ${Number.isFinite(q)?unit(q,'m³/jam'):'—'}</span></div>`},'compactor');
    addFormula('rdDensityOut',()=>{const TL=n('rdTL'),lane=n('rdLane'),head=n('rdHead'),unitLen=n('rdUnitLen'),actual=n('rdActual'),hs=head+unitLen,d=hs?(1000*TL*.8*lane)/hs:NaN;return `<div class="formula-line"><span class="formula-label">Rumus</span><span class="formula-eq">Dmax = (1000 × TL × 80% × Lane) ÷ Head Spacing</span></div><div class="formula-line"><span class="formula-label">Substitusi</span><span class="formula-eq">Head Spacing = ${f(head)} + ${f(unitLen)} = ${f(hs)} m<br>Dmax = (1000 × ${f(TL)} × 0,80 × ${f(lane)}) ÷ ${f(hs)} = ${Number.isFinite(d)?unit(d,'unit'):'—'}</span></div><div class="formula-line"><span class="formula-label">Kontrol</span><span class="formula-eq">Actual = ${f(actual,0)} unit → <b>${Number.isFinite(d)&&actual<=d?'OK — BELOW MAX':'OVER — ABOVE MAX'}</b></span></div>`},'road-density');
    const ma=$('ma');
    if(ma){const card=ma.closest('.tool-card,.calc-card,.module-section,article,section')||ma.parentElement;if(card){let box=card.querySelector('[data-formula-box="availability"]');if(!box){box=document.createElement('div');box.className='formula-calc availability-formula';box.dataset.formulaBox='availability';ma.parentElement?.insertAdjacentElement('beforebegin',box)}const run=()=>{const W=n('working'),R=n('repair'),S=n('standby');const maV=W+R?100*W/(W+R):NaN,paV=W+R+S?100*(W+S)/(W+R+S):NaN,uaV=W+S?100*W/(W+S):NaN,euV=W+R+S?100*W/(W+R+S):NaN;const item=(name,desc,formula,v)=>`<div class="avail-item"><div class="avail-name">${name}</div><div class="avail-formula">${desc}<br><b>${formula}</b> = <span class="formula-result">${Number.isFinite(v)?f(v)+' %':'—'}</span></div></div>`;box.innerHTML=`<div class="formula-title"><span>ƒ</span> AVAILABILITY — RUMUS & SUBSTITUSI</div><div class="avail-grid">${item('MA — Mechanical Availability','Rumus: W ÷ (W + R) × 100',`${f(W)} ÷ (${f(W)} + ${f(R)}) × 100`,maV)}${item('PA — Physical Availability','Rumus: (W + S) ÷ (W + R + S) × 100',`(${f(W)} + ${f(S)}) ÷ (${f(W)} + ${f(R)} + ${f(S)}) × 100`,paV)}${item('UA — Use of Availability','Rumus: W ÷ (W + S) × 100',`${f(W)} ÷ (${f(W)} + ${f(S)}) × 100`,uaV)}${item('EU — Effective Utilization','Rumus: W ÷ (W + R + S) × 100',`${f(W)} ÷ (${f(W)} + ${f(R)} + ${f(S)}) × 100`,euV)}</div><div style="margin-top:12px;font-size:11px;color:#64748b"><b>W</b> = Working · <b>R</b> = Repair/Down · <b>S</b> = Standby</div>`};card.querySelectorAll('input,select').forEach(x=>{x.addEventListener('input',run);x.addEventListener('change',run)});run()}}
    }
    const q=$('qsuar2026');if(q){let box=q.querySelector('[data-formula-box="qsuar"]');if(!box){box=document.createElement('div');box.className='formula-calc';box.dataset.formulaBox='qsuar';q.appendChild(box)}const run=()=>{const cap=n('q26GraderCap'),w=n('q26RoadWidth'),d=n('q26Distance'),g=n('q26Graders')||1,rate=w?cap/w:0,t=rate&&d?d/(rate*g):NaN;box.innerHTML=`<div class="formula-title"><span>ƒ</span> RUMUS & SUBSTITUSI</div><div class="formula-line"><span class="formula-label">Kapasitas per lebar</span><span class="formula-eq">${f(cap,0)} ÷ ${f(w)} = ${f(rate)} BCM/jam</span></div><div class="formula-line"><span class="formula-label">Scrapping Time</span><span class="formula-eq">${f(d)} ÷ (${f(rate)} × ${f(g,0)}) = ${Number.isFinite(t)?unit(t,'jam'):'—'}</span></div>`};q.querySelectorAll('input,select').forEach(x=>{x.addEventListener('input',run);x.addEventListener('change',run)});run()}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,300));else setTimeout(install,300);
  new MutationObserver(()=>setTimeout(install,100)).observe(document.documentElement,{childList:true,subtree:true});
})();