/* Formula display — Dozer, Grader, Motor Grader, Compactor & Road */
(()=>{
const $=id=>document.getElementById(id), n=id=>{const v=parseFloat(String($(id)?.value??'').replace(/\s/g,'').replace(',','.'));return Number.isFinite(v)?v:0}, f=(v,d=2)=>Number(v).toLocaleString('id-ID',{minimumFractionDigits:d,maximumFractionDigits:d});
const box=(sel,id,formula,calc)=>{const el=document.querySelector(sel);if(!el||el.dataset.formulaReady)return;el.dataset.formulaReady='1';const p=document.createElement('div');p.className='formula-calc';p.id=id;p.innerHTML=`<strong>SUBSTITUSI PERHITUNGAN</strong><br>—`;el.appendChild(p);const run=()=>{p.innerHTML=`<strong>SUBSTITUSI PERHITUNGAN</strong><br>${calc()}`};const card=el.closest('.module-section')||el.closest('.tool-card')||document;card.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',run));card.querySelectorAll('select').forEach(x=>x.addEventListener('change',run));run()};
function install(){
 box('#support-equipment article:nth-of-type(1) .formula-display','dzFormulaCalc','',()=>{const B=n('dzB'),H=n('dzH'),D=n('dzD'),Fb=n('dzFb'),Vf=n('dzVf'),Vr=n('dzVr'),Z=n('dzZ'),E=n('dzE'),q=B*H*D*Fb,ct=D/Vf+D/Vr+Z,v=ct?(q*60*E)/ct:NaN;return `q = ${f(B)} × ${f(H)} × ${f(D)} × ${f(Fb)} = <b>${f(q)} m³</b><br>CT = ${f(D)} ÷ ${f(Vf)} + ${f(D)} ÷ ${f(Vr)} + ${f(Z)} = <b>${f(ct)} min</b><br>QD = (${f(q)} × 60 × ${f(E)}) ÷ ${f(ct)} = <b>${Number.isFinite(v)?f(v)+' m³/jam':'—'}</b>`});
 box('#support-equipment article:nth-of-type(2) .formula-display','grFormulaCalc','',()=>{const P=n('grP'),J=n('grJ'),Vf=n('grVf'),Vr=n('grVr'),Z=n('grZ'),E=n('grE'),FK=n('grFK'),ct=J/Vf+J/Vr+Z,v=ct?(P**2*J*60*E*FK)/ct:NaN;return `CT = ${f(J)} ÷ ${f(Vf)} + ${f(J)} ÷ ${f(Vr)} + ${f(Z)} = <b>${f(ct)} min</b><br>QG = (${f(P)}² × ${f(J)} × 60 × ${f(E)} × ${f(FK)}) ÷ ${f(ct)} = <b>${Number.isFinite(v)?f(v)+' m²/jam':'—'}</b>`});
 box('#support-equipment article:nth-of-type(3) .formula-display','mgFormulaCalc','',()=>{const V=n('mgV'),Le=n('mgLe'),Lo=n('mgLo'),E=n('mgE'),W=n('mgW'),Le2=n('mgLe2'),Lo2=n('mgLo2'),np=n('mgNPass'),D=n('mgD'),V2=n('mgV2'),width=Le2-Lo2,trips=width?W/width*np:NaN,h=V2?trips*D/(V2*1000*E):NaN,q=V*(Le-Lo)*1000*E;return `Q = ${f(V)} × (${f(Le)} − ${f(Lo)}) × 1000 × ${f(E)} = <b>${f(q)} m²/jam</b><br>Jumlah trip = (${f(W)} ÷ (${f(Le2)} − ${f(Lo2)})) × ${f(np)} = <b>${Number.isFinite(trips)?f(trips):'—'} trip</b><br>Waktu = (${f(trips)} × ${f(D)}) ÷ (${f(V2)} × 1000 × ${f(E)}) = <b>${Number.isFinite(h)?f(h)+' jam':'—'}</b>`});
 box('#compactor .formula-display','cpFormulaCalc','',()=>{const W=n('cpW'),V=n('cpV'),H=n('cpH'),E=n('cpE'),N=n('cpN'),v=N?(W*V*H*1000*E)/N:NaN;return `Q = (${f(W)} × ${f(V)} × ${f(H)} × 1000 × ${f(E)}) ÷ ${f(N)} = <b>${Number.isFinite(v)?f(v)+' m³/jam':'—'}</b>`});
 box('#road .formula-display','roadFormulaCalc','',()=>{const tl=n('rdTL'),head=n('rdHead'),lane=n('rdLane'),actual=n('rdActual'),unit=n('rdUnitLen'),hs=head+unit,d=hs?(1000*tl*.8*lane)/hs:NaN;return `Dmax = (1000 × ${f(tl)} × 80% × ${f(lane)}) ÷ ${f(hs)} = <b>${Number.isFinite(d)?f(d)+' unit':'—'}</b><br>Actual = <b>${f(actual,0)} unit</b> → <b>${actual<=d?'OK — BELOW MAX':'OVER — ABOVE MAX'}</b>`});
 const q=$('#qsuar2026');if(q&&!q.dataset.formulaReady){q.dataset.formulaReady='1';const p=document.createElement('div');p.className='formula-calc';q.querySelectorAll('.formula-box')[0]?.appendChild(p);const run=()=>{const cap=n('q26GraderCap'),w=n('q26RoadWidth'),d=n('q26Distance'),g=n('q26Graders')||1,c=w?cap/w:0,t=c&&d?d/(c*g):NaN;p.innerHTML=`<strong>SUBSTITUSI PERHITUNGAN</strong><br>${f(cap,0)} ÷ ${f(w)} = <b>${f(c)} BCM/jam</b><br>${f(d)} ÷ (${f(c)} × ${f(g,0)}) = <b>${Number.isFinite(t)?f(t,3)+' jam':'—'}</b>`};q.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',run));q.querySelectorAll('select').forEach(x=>x.addEventListener('change',run));run()}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,250));else setTimeout(install,250);new MutationObserver(()=>setTimeout(install,80)).observe(document.documentElement,{childList:true,subtree:true});
})();
